# Imports

In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets

import spacy
from sklearn.feature_extraction.text import TfidfVectorizer

# Preprocessing

## Combining Datasets
The data being used consists of 5 separate datasets all containing 2000 each. Our first step was to combine them into one large one. We also dropped the category column at this point to prevent the model from clustering with it.

In [2]:
bussiness_df = pd.read_csv("business_data.csv")
education_df = pd.read_csv("education_data.csv")
entertainment_df = pd.read_csv("entertainment_data.csv")
sports_df = pd.read_csv("sports_data.csv")
tech_df = pd.read_csv("technology_data.csv")

In [3]:
df = pd.concat([bussiness_df,education_df,entertainment_df,sports_df,tech_df],axis=0)
df.head()

,headlines,description,content,url,category
0,Nirmala Sitharaman to equal Morarji Desai’s re...,With the presentation of the interim budget on...,"Sitharaman, the first full-time woman finance ...",https://indianexpress.com/article/business/bud...,business
1,"‘Will densify network, want to be at least no....","'In terms of market share, we aim to double it...",The merger of Tata group’s budget airlines Air...,https://indianexpress.com/article/business/avi...,business
2,Air India group to induct an aircraft every si...,Air India currently has 117 operational aircra...,The Air India group plans to induct one aircra...,https://indianexpress.com/article/business/avi...,business
3,Red Sea woes: Exporters seek increased credit ...,Rising attacks forced shippers to consider the...,Indian exporters have asked the central govern...,https://indianexpress.com/article/business/red...,business
4,Air India group to induct a plane every 6 days...,"Apart from fleet expansion, 2024 will also see...",The Air India group plans to induct one aircra...,https://indianexpress.com/article/business/avi...,business

In [4]:
df.drop(["url","category"], axis=1,inplace=True)
df.head()

,headlines,description,content
0,Nirmala Sitharaman to equal Morarji Desai’s re...,With the presentation of the interim budget on...,"Sitharaman, the first full-time woman finance ..."
1,"‘Will densify network, want to be at least no....","'In terms of market share, we aim to double it...",The merger of Tata group’s budget airlines Air...
2,Air India group to induct an aircraft every si...,Air India currently has 117 operational aircra...,The Air India group plans to induct one aircra...
3,Red Sea woes: Exporters seek increased credit ...,Rising attacks forced shippers to consider the...,Indian exporters have asked the central govern...
4,Air India group to induct a plane every 6 days...,"Apart from fleet expansion, 2024 will also see...",The Air India group plans to induct one aircra...

In [5]:
print(df.shape,"\n")

(10000, 3)

In [6]:
df.isna().sum()

headlines      0
description    0
content        0
dtype: int64

## Text Cleaning

* Lowercasing — obvious, but easy to forget
* Removing punctuation, special characters, HTML/URLs depending on your data source
* Stopword removal 
* Lemmatization

In [7]:
def cleanColumn(df, col):
    df[col] = df[col].str.lower()
    
    #Load the model, convert to lemmas, join into one text
    nlp = spacy.load("en_core_web_sm")
    df[col] = df[col].apply(lambda x: nlp(x))
    df[col] = df[col].apply(lambda x: [token.lemma_ for token in x])
    df[col] = df[col].apply(lambda x: " ".join(x))


    #Removing punctuation
    df[col] = df[col].str.replace(".","")
    df[col] = df[col].str.replace(",","")
    df[col] = df[col].str.replace("!","")
    df[col] = df[col].str.replace("?","")
    df[col] = df[col].str.replace(";","")
    df[col] = df[col].str.replace(":", "")
    df[col] = df[col].str.replace("\n", "")

    return df[col]

In [8]:
df2 = df.copy()
for col in df.columns:
    df2[col] = cleanColumn(df2, col)

In [9]:
df2.head()

,headlines,description,content
0,nirmala sitharaman to equal morarji desai ’s r...,with the presentation of the interim budget on...,sitharaman the first full - time woman financ...
1,' will densify network want to be at least no...,' in term of market share we aim to double it...,the merger of tata group ’s budget airlines ai...
2,air india group to induct an aircraft every si...,air india currently have 117 operational aircr...,the air india group plan to induct one aircraf...
3,red sea woe exporter seek increase credit as ...,rise attack force shipper to consider the long...,indian exporter have ask the central governmen...
4,air india group to induct a plane every 6 day ...,apart from fleet expansion 2024 will also see...,the air india group plan to induct one aircraf...

In [ ]:
df2["Text"]  = df2["headlines"] + " " + df2["description"] + " " + df2["content"]
text = df2["Text"].to_list()
text

['nirmala sitharaman to equal morarji desai ’s record with her sixth straight budget with the presentation of the interim budget on february 1  nirmala sitharaman will surpass the record of her predecessor like manmohan singh  arun jaitley  p chidambaram  and yashwant sinha  who have present five budget in a row  sitharaman  the first full - time woman finance minister of the country  have present five full budget since july 2019 and will present an interim or vote - on - account budget next week   with the presentation of the interim budget on february 1  sitharaman will surpass the record of her predecessor like manmohan singh  arun jaitley  p chidambaram  and yashwant sinha  who have present five budget in a row   desai  as finance minister  have present five annual budget and one interim budget between 1959 - 1964  the interim budget 2024 - 25 to be present by sitharaman on february 1  will be a vote - on - account that will give the government authority to spend certain sum of money till a new government come to office after the april - may general election   advertisement  as the parliamentary election be due  sitharaman ’s interim budget may not contain any major policy change  speak at an industry event last month  sitharaman have rule out any " spectacular announcement " in the interim budget  say it would just be a vote - on - account before the general election   a vote - on - account  once approve by parliament  will authorise the government to withdraw money from the consolidated fund of india on a pro - rata basis to meet expenditure for the april - july period   the new government  which be likely to be form around june  will come up with a final budget for 2024 - 25 sometime in july  usually  interim budget do not contain major policy announcement  but nothing stop the government from take step which be necessary to deal with the urgent issue face the economy   after the modi government come to power in 2014  arun jaitley take charge of the finance ministry and present five budget in a row from 2014 - 15 to 2018 - 19  it be in 2017  that jaitley depart from the colonial - era tradition of present budget on the last working day of february to 1st of the month   advertisement  piyush goyal  who be hold the additional charge of the ministry due to ill health of jaitley  present the interim budget for 2019 - 20 on february 1  2019  goyal have hike standard deduction for salaried taxpayer by rs 10000 to rs 50000  also  the tax rebate for taxpayer whose annual taxable income do not exceed rs 5 lakh be increase from rs 2500 to rs 12500   after the 2019 general election  in the modi 20 government  sitharaman be give the charge of the finance portfolio  she become the second woman to have present a budget after indira gandhi  who have present the budget for the financial year 1970 - 71   that year  sitharaman do away with the traditional budget briefcase and instead go for a \' bahi - khata \' with the national emblem to carry the speech and other document   advertisement  under sitharaman  india have weather the covid pandemic with an array of policy measure announce for the poor and continue its tag of the fast grow major economy and a \' bright spot \' in the world economy   india be race to become a usd 5 trillion economy by 2027 - 28 and usd 30 trillion by 2047  former prime minister morarji desai who hold the tag of present 10 budget — the maximum by any finance minister — have present six of they  include one interim  in a row   the first budget of independent india be present by the first finance minister r k shanmukham chetty   sitharaman  who will be present her sixth budget in a row  be expect to come up with some measure  especially to boost the rural sector as the agriculture sector growth in 2023 - 24 be estimate to decelerate to 18 per cent  from 4 per cent  in the precede year   rakesh nangia  chairman  nangia andersen india say give the proximity to the election  the budget be expect to focus on immediate fiscal need rather than introduce broad long - term economic reform   advertisement  in the last interim budget for fy 2019 - 20  while the overall tax structure remain unchanged  there be certain specific tax rebate and standard deduction concession  " while major announcement may be defer until after the 2024 lok sabha election  the budget be expect to address ongoing concern and lie the foundation for future economic growth  this strategic approach aim to balance immediate fiscal responsibility with long - term economic objective in a pre - election context  " nangia say   ',
 "' will densify network  want to be at least no  2 in any city pair '  air india express md ' in term of market share  we aim to double it by 2028 in both segments—15 per cent in the domestic and 20 per cent in short - haul international  ' say ai express ’s manage director aloke singh the merger of tata group ’s budget airlines air india express ( ai express ) and aix connect ( formerly airasia india ) into one carrier — ai express — be on track for completion in the next three to four month  even as operational integration of the two be nearly complete  accord to ai express ’s manage director aloke singh  the airline in its brand - new avatar aspire to double its market share by 2028  more than triple its fleet size to 180 aircraft  and build a dense network focusse on tier - two and tier - three city  all while work in synergy with parent air india to realise the group ’s vision of emerge as a formidable player in india and beyond   in an interaction with sukalp sharma  singh give a lowdown of ai express ’s vision and strategy to chart ambitious growth in the come year  edit excerpt   how be the integration of ai express and aix connect come along   the past year have be all about the integration  which involve integrate system  process  platform  people  brand  network and fleet  we have tweak the combined network to facilitate flow between the two network  that integration be now move into a merger  which we hope to complete in three to four month  simultaneously  a massive growth agenda have kick in  we be now induct aircraft at a rate of three - and - a - half per month  and it will continue for a while   advertisement  with steady supply of new aircraft  what shape will your network take   the new capacity will help we grow significantly  this growth will come from our exist market as well as some new one  in our exist market  we will densify the network and plug gap that we could not address early due to capacity constraint  the broad network strategy be that we will first consolidate our presence and become strong wherever we already operate  we want to be at least the number two player in any city pair  we do not want to open too many new station together  we want to open one station  deploy capacity there to increase connectivity  and spread out from there  as we become firm in a market  it will also help we in rationalise cost   ai express be almost exclusively a short - haul international carrier while aix connect be a domestic airline  should we expect the combine entity to be more focusse on the domestic market   if you put the two network together  we roughly have 50 per cent capacity each on domestic and international  this will remain so for the next year or two  the domestic portion will then grow to some extent  we will probably end up with about 60 per cent domestic and 40 per cent international  the domestic market be much big and our capacity deployment will reflect that   in term of market share  we aim to double it by 2028 in both segments—15 per cent in the domestic and 20 per cent in short - haul international   what be the status of network optimisation at the group level between the full - service carrier ( air india ) and the budget carrier ( ai express )   it have start and will be a continuous process as the nature of market be dynamic  route rationalisation at the group level have begin  different operational model suit different market  if we see that a market be well serve in financial term by the low - cost model  then we will deploy the relevant product  there will be market where operating premium product will offer an upside  so the full - service product will be offer there  in market and segment that be big and deep enough  we would look at straddle both product offering   advertisement   the market see indigo  which have a domestic market share of over 60 per cent  as your big competitor  how do you look at that challenge   the market be big enough and deep enough  and have space for a number of player  the broad thrust of our network strategy will be a lot more focus on tier - two and tier - three city  we will also focus on international operation from tier - two city  because that be a space we understand very well  we will not be concentrate our capacity on large city  of course  there will be some capacity deploy there  but a large part will be for tier - two  tier - three city   so  you be look at a point - to - point network instead of hub - and - speak   yes  it will not be focusse on a large hub  however  our network will have a number a focus city  probably 10  where we will also transfer passenger  like  kochi may not be a hub per se  but it have significant potential for domestic - to - domestic  international - to - domestic  and even international - to - international transfer  similarly  we be connect bangalore  where we have a dense network  to our point in kerala  for example  we can offer travel from ayodhya to kochi via bangalore  or a lucknow - bangalore - trivandrum connection   air india express operate boeing 737s while aix connect have airbus a320s  do you now plan to operate both or retire the a320s   we will have a mixed fleet  you have to look at the fleet from the group perspective  the fleet will be fungible  we want that flexibility  have a mixed fleet may have some sub - optimality  but with scale  fleet commonality benefit diminish  if you have 200 or 300 or 400 aircraft  due to the large scale of operation  a mixed fleet be not too different from a single - type fleet   advertisement  our plan be to have a fleet size of about 180 aircraft by 2028  we have a legacy fleet of 26 737ng ( 737 next generation )  of which 10 be lease  and 28 a320s  all of which be lease  the lease aircraft will start go back to lessor start this year   the air india group ’s 470 - aircraft order include 190 boeing 737 max plane  be all of those go to come to air india express   so far  we have not take that call at the group level  the aircraft delivery will stretch over year  some of the airbus a320s and a321s ( also part of the order ) may even come our ( air india express ) way  aircraft type within the group will remain fungible give the long delivery schedule and the decision will be base on synergy within the group like aircraft engineering and maintenance  but certainly  air india express will operate under an all - economy model   consider air india express have mostly be a short - haul international carrier and give the growth trajectory you be eye  be you look to get into wide - body operation as well   no  we have no such plan at present  we first want to grow and scale up with our current model ( low - cost domestic and short - haul international operation )  before think about anything else   by when can we see your legacy fleet in the new air india express branding   we be not go to change the livery on the legacy fleet  one reason be that many of those aircraft will be go back to lessor once the lease expire  secondly  we want to prioritise the new aircraft  as the painting capacity in the mro ( maintenance  repair  and overhaul unit ) be limited  we want to paint the new aircraft first and then take a call on the old one  in any airline ’s livery change programme  it take year for 100 per cent of the aircraft to get rebrande   give your thrust on tier - two and tier - three city  will we see air india express apply for route under the regional connectivity scheme udan ( ude desh ka aam naagrik )   certainly  we could look at it  if it fit into our route strategy  we would be really interested in international udan  but there could be some domestic route also that could make sense for we ",
 'air india group to induct an aircraft every six day throughout this year air india currently have 117 operational aircraft in its fleet  while its arm air india express have 63 plane  under the new owner  air india have be able to bring back to service 90 per cent of its long - ground aircraft as well  the air india group plan to induct one aircraft every six day on an average throughout 2024  include five more airbus a350 wide - body aircraft  and 46 boeing 737 and 17 airbus a320 narrow - body plane  air india ’s chief executive officer and managing director campbell wilson say thursday in a message to staff ahead of the second anniversary of the carrier ’s return to the tata group  apart from these 68 plane — part of the air india group ’s mammoth 470 - aircraft order place in 2023 — four lease boeing 777 wide - body plane will also join the carrier ’s fleet   air india currently have 117 operational aircraft in its fleet  while its arm air india express have 63 plane  under the new owner  air india have be able to bring back to service 90 per cent of its long - ground aircraft as well   apart from fleet expansion  2024 will also see air india kick off the full interior refit of 40 legacy wide - body aircraft — boeing 777s and 787s  the upgradation exercise  which will include complete replacement of seat and in - flight entertainment system on the legacy wide - body fleet  be expect to start in july  coincide with air india ’s first a350 aircraft start international operation  the plane  which start commercial operation this week  be initially fly domestic sector for a few month for crew familiarisation flight  air india also plan to start interior upgrade on 41 narrow - body a320 aircraft as well this year   advertisement  " though we still have a long way to go to upgrade the legacy fleet  improve our consistency  close remain gap and strengthen fragile process  the future be now more visible  more tangible and  I hope  more inspiring  despite — and no doubt somewhat because of — the good progress we ’ve make in two short year since privatisation  expectation be high  so we need to keep rise to meet they  " wilson say   over the past two year  air india have augment its legacy fleet by take 36 aircraft on lease  apart from pace the giant 470 - aircraft order with airbus and boeing  it have add five domestic and 11 international route to its network  and open five new international station  new brand identity for both air india and air india express be also launch last year   ever since air india return to the tata group on january 27  2022  the new owner have be focus on spruce up the product offering  while also plan an extensive expansion for the airline  a five - year roadmap – vihaanai – be prepare with the objective of substantially grow the airline ’s network and fleet in a bid to put it on a " path to sustained growth  profitability  and market leadership "   as per datum share by wilson with staff  air india clock 249 per cent revenue growth over the past two year  while air india express ’s revenue grow 148 per cent over the period  wilson do not give further detail on the group ’s financial   advertisement  " in the context of our starting point  the size and scope of the transformation we ’re undertake  our unprecedented multi - carrier integration  our huge growth and product - improvement aspiration and our capability - building requirement  two year be an incredible short time  indeed  we be not even 18 month into our 5 - year vihaanai transformation program  but even so  as the infographic show  the progress make in two short year be quite remarkable and be testament to the commitment  energy and hard work of all air indians  " wilson say   the tata group be in the process of consolidate its airline business by merge air india and vistara to create one full - service carrier under the air india brand  and air india express and aix connect ( formerly airasia india ) to create one budget airline under the air india express brand  while the operational integration of air india express and aix connect be complete  the merger of air india and vistara be expect sometime in 2025 ',
 'red sea woe  exporter seek increase credit as freight rate jump 300 % rise attack force shipper to consider the long route indian exporter have ask the central government to help facilitate more credit as freight rate have jump nearly 300 per cent due to the disruption in the red sea route force global shipping line to take long trade route  which be ultimately affect export of low value item such as basmati rice   increase attack on ship sail in the red sea region since november 2023 have force shipper to consider the alternative  long route past the cape of good hope  which have not only stretch delivery time by 15 to 20 day  but also increase the transit cost substantially because of incremental freight rate and insurance premium   federation of indian export organisation ( fieo ) director general ajay sahai tell the indian express that freight cost have surge by 300 per cent as global shipping line be take the cape of good hope route  which be why exporter have seek more credit to match the rise cost of shipment to europe   advertisement  meanwhile  rating agency crisil on thursday say that player operate in sector such as agricultural commodity and marine food could see a significant impact due to the perishable nature of their good or lean margin profile  which limit their ability to absorb the risk from rise freight cost   " not all sector be expect to be impact to the same extent  in fact  for agricultural commodity like basmati rice ( 30 - 35 % of production be ship to these region )  exporter be feel the pressure as rise freight cost have curb export and a part of their inventory be now be sell in the domestic market  lead to a moderation in realisation  " the report say   indian company use the red sea route through the suez canal to trade with europe  north america  north africa  and part of the west asia  crisil say that these region account for 50 per cent of india ’s export worth rs 18 lakh crore and 30 per cent of import worth rs 17 lakh crore last fiscal   " marine food – predominantly shrimp and prawn – could also see a significant impact as 80 - 90 per cent of the production be export  more than half of it through the red sea  their perishable nature and lean margin make exporter vulnerable to rise freight cost and competitive pressure from latin american supplier  " the report add   advertisement  the indian express have early report that the finance ministry be set to hold a high - level meeting on february 5 to ensure smooth trade payment amid challenge emanate from the disruption in the red sea region ',

In [ ]:
#Ensuring we still have the correct number of entries
len(text)

10000